import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "./_components/footer";
import AuthProvider from "./_providers/authProvider";
import { Toaster } from "./_components/ui/sonner";
import React from "react";

export const metadata: Metadata = {
  title: "Rti-Barbershop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`{inter.className} dark`}>
        <AuthProvider>
          <div className="flex-1">{children}</div>
          <Toaster />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
